[build]
target = "index.html"
dist = "dist"

[[hooks]]
stage = "build"
command = "cp"
command_arguments = ["welcome-page/dist/index.html", "dist/index.html"]

[serve]
address = "127.0.0.1"
port = 8000
