name: GitHub Pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Install trunk
        uses: jetli/trunk-action@v0.5.0
        with:
          version: "latest"

      - name: Set BASE_PATH
        run: echo "BASE_PATH=/${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Build main page
        run: |
          BASE_PATH=${{ env.BASE_PATH }}/p trunk build --release --public-url=${{ env.BASE_PATH }}/p

      - name: Prepare dist directory
        run: |
          mkdir -p dist_temp/p
          cp dist/index.html dist_temp/p/index.html

      - name: Build welcome app
        run: BASE_PATH=${{ env.BASE_PATH }} trunk build --release --public-url=${{ env.BASE_PATH }}

      - name: Prepare dist directory
        run: |
          mkdir -p dist_temp/p/{welcome,about}
          cp -r welcome-page/dist/* dist_temp/
          cp -r dist/* dist_temp/p/
          cp dist_temp/p/index.html dist_temp/p/welcome/index.html
          cp dist_temp/p/index.html dist_temp/p/about/index.html
          rm -rf dist
          mv dist_temp dist
          cp dist/index.html dist/404.html

      - name: Update 404.html
        run: sed -i 's|BASE_PATH_PLACEHOLDER|'${{ env.BASE_PATH }}'|g' dist/404.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
