on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  BASE_URL: "/"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install trunk
        uses: jetli/trunk-action@v0.5.0
        with:
          version: "latest"

      # Build Main Application
      - name: Build main application
        run: |
          export BASE_PATH=""
          trunk build --release --public-url="/"

      # Setup routes
      - name: Setup routes
        run: |
          mkdir -p dist/{welcome,about,home}
          cp dist/index.html dist/welcome/index.html
          cp dist/index.html dist/about/index.html
          cp dist/index.html dist/home/index.html

      # Prepare distribution
      - name: Prepare final distribution
        run: |
          cp dist/index.html dist/404.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
          enable_jekyll: false
